# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world Yeaa!!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
  displayName: 'Run a multi-line script'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/azure-terraform/kubernetes'
    backendType: 'azurerm'
    backendServiceArm: 'prueba service conection'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-cg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'sotarageacctcarlosxx'
    backendAzureRmContainerName: 'sotarageacctcarlosxxcontainer'
    backendAzureRmKey: 'kubernets-dev.tfstate'
    allowTelemetryCollection: true
